services:
  - type: web
    name: dashboard-react
    env: static
    buildCommand: npm ci && npx react-scripts build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
