services:
  - type: web
    name: dashboard-react
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 16.20.0
